### UPLOAD CSV - POST
POST http://localhost/theled/inventory/api/inventory/upload/upload.csvtodatabase.dao.php
Content-Type: multipart/form-data; boundary=testing

--testing
Content-Disposition: form-data; name="platform"

onsign
--testing
Content-Disposition: form-data; name="uploadType"

screens
--testing
Content-Disposition: form-data; name="separator"

;
--testing
Content-Disposition: form-data; name="upload-file"; filename="./public/teste.csv"
Content-Type: text/csv

#< C:/srv/arquivo.csv
#< C:/srv/hivestack_screens_2025-12-09T16_39_03.883.csv
#< C:/srv/hivestack_sites_2025-12-10T13_58_57.616.csv
#< C:/srv/Adsmovil_ExportedDigitalBillboards1765297859445(Digital Billboard).csv
#< C:/srv/admooh_Devices.csv
#< C:/srv/admooh_Placements.csv
< C:/srv/OnSign_RelatoriodePlayers.csv
--testing--

################################################

### LIST INVENTORY - POST
POST http://localhost/theled/inventory/api/inventory/list/list.platforminventory.dao.php
Content-Type: multipart/form-data; boundary=testing

--testing
Content-Disposition: form-data; name="auth"

7c4a8d09ca3762af61e59520943dc26494f8941b
--testing
Content-Disposition: form-data; name="secretkey"

d93a5def7511da3d0f2d171d9c344e91-69c5fcebaa65b560eaf06c3fbeb481ae44b8d618
--testing
Content-Disposition: form-data; name="platform"

hivestack
--testing
Content-Disposition: form-data; name="subjectType"

screens
--testing
Content-Disposition: form-data; name="page"

4
--testing
Content-Disposition: form-data; name="orderby"

// OnSign
//`Nome do Player`

// Hivestack
`screen ID` 

--testing
Content-Disposition: form-data; name="orderdirection"

ASC
--testing

################################################